### ISSUE TITLE
Error Running Model 

### ISSUE THREAD

**Issue by thewozz** [jeffxtang/mobiletfbook#2]
I followed Chapt 2 tutorial and trained my model. The model is working fine but when I try to use it inside the ios app it says "Error Running Model". I have the latest Tensorflow version and Xcode as well. Is there any specific version I should use for training or it doesn't matter.  The error is the same for both Inception V3 model and MobileNet for the default, stripped and the quantized versions. Any updates?

**Comment by jeffxtang** [comment]
Which Xcode and TensorFlow version are you using? I have tested the code with Xcode 8.2.1, 9.2 and 9.3,  and TensorFlow 1.4.0, 1.5.0, 1.6.0, 1.7.0, and 1.8.0. Have you tried any of those? You can easily download a specific TensorFlow version that I have tested with (1.4 to 1.8) at https://github.com/tensorflow/tensorflow/releases to build and test the model. Sorry I haven't got the chance to try the latest TensorFlow version.

**Comment by thewozz** [comment]
**I tried Tensorflow 1.5.1 and the error I get after running the HelloTensorflow_Swift is as follows : 
There is a list of errors but mainly it starts with this:** 

Executor failed to create kernel. Invalid argument: NodeDef mentions attr 'dilations' not in Op<name=Conv2D; signature=input:T, filter:T -> output:T; attr=T:type,allowed=[DT_HALF, DT_FLOAT, DT_DOUBLE]; attr=strides:list(int); attr=use_cudnn_on_gpu:bool,default=true; attr=padding:string,allowed=["SAME", "VALID"]; attr=data_format:string,default="NHWC",allowed=["NHWC", "NCHW"]>; NodeDef: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params). (Check whether your GraphDef-interpreting binary is up to date with your GraphDef-generating binary.).
	 [[Node: conv/Conv2D = Conv2D[T=DT_FLOAT, data_format="NHWC", dilations=[1, 1, 1, 1], padding="VALID", strides=[1, 2, 2, 1], use_cudnn_on_gpu=true, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_Mul_0, conv/conv2d_params)]]

**I built the Tensorflow iOS libraries manually and it worked without using the pods.
Thanks**
